=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2026.09.07 15:33:06 =~=~=~=~=~=~=~=~=~=~=~=
show ip

NAME        : PC2[1]
IP/MASK     : 192.168.2.2/24
GATEWAY     : 192.168.2.1
DNS         : 
MAC         : 00:50:79:66:68:01
LPORT       : 26524
RHOST:PORT  : 127.0.0.1:26525
MTU         : 1500

PC2> 