=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2026.09.07 15:33:30 =~=~=~=~=~=~=~=~=~=~=~=
show ip

NAME        : PC3[1]
IP/MASK     : 192.168.3.2/24
GATEWAY     : 192.168.3.1
DNS         : 
MAC         : 00:50:79:66:68:02
LPORT       : 26526
RHOST:PORT  : 127.0.0.1:26527
MTU         : 1500

PC3> 