=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2026.09.07 15:33:54 =~=~=~=~=~=~=~=~=~=~=~=
show ip

NAME        : PC4[1]
IP/MASK     : 192.168.4.2/24
GATEWAY     : 192.168.4.1
DNS         : 
MAC         : 00:50:79:66:68:03
LPORT       : 26528
RHOST:PORT  : 127.0.0.1:26529
MTU         : 1500

PC4> 