=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2026.09.07 15:34:20 =~=~=~=~=~=~=~=~=~=~=~=
show ip

NAME        : PC5[1]
IP/MASK     : 192.168.5.2/24
GATEWAY     : 192.168.5.1
DNS         : 
MAC         : 00:50:79:66:68:04
LPORT       : 26530
RHOST:PORT  : 127.0.0.1:26531
MTU         : 1500

PC5> 